"use strict";

// Meta's `x-dtls-auth` SDP attribute for end-to-end encrypted calls.
//
// One-to-one E2EE calls authenticate the DTLS handshake with the account's
// Signal identity key: the offer (and answer) must carry an `a=x-dtls-auth:`
// value generated by Meta's frame_encryption wasm, or the other side refuses
// the media path.
//
// The wasm is downloaded once and cached, and the generation itself runs in a
// child Node process because wasm callbacks from JS need the
// `--experimental-wasm-type-reflection` flag.

var fs = require("fs");
var path = require("path");
var https = require("https");
var { spawn } = require("child_process");
var log = require("npmlog");
var e2eeState = require("./e2eeState");

var wasmURL = "https://static.xx.fbcdn.net/rsrc.php/yV/r/Wfd6t0e74Jr.wasm";
var runnerPath = path.join(__dirname, "dtlsAuthRunner.js");

function download(url, file, callback) {
  var request = https.get(url, function(response) {
    if (response.statusCode !== 200) {
      response.resume();
      return callback(new Error("HTTP " + response.statusCode));
    }
    var chunks = [];
    response.on("data", function(chunk) { chunks.push(chunk); });
    response.on("end", function() {
      try {
        fs.mkdirSync(path.dirname(file), { recursive: true });
        fs.writeFileSync(file, Buffer.concat(chunks));
        callback(null);
      } catch (e) {
        callback(e);
      }
    });
  });
  request.on("error", callback);
  request.setTimeout(60000, function() {
    request.destroy(new Error("download timed out"));
  });
}

// Resolves the cached wasm path, downloading it on first use.
function ensureWasm(options, callback) {
  var file = options.wasmPath;
  if (file && fs.existsSync(file)) return callback(null, file);
  if (!file) {
    var base = options.e2eeDevicePath
      ? path.dirname(options.e2eeDevicePath)
      : process.cwd();
    file = path.join(base, "frame_encryption.wasm");
    if (fs.existsSync(file)) return callback(null, file);
  }
  log.info("call", "Downloading the frame-encryption wasm (first E2EE call)...");
  download(options.wasmUrl || wasmURL, file, function(err) {
    if (err) return callback(err);
    callback(null, file);
  });
}

function runGenerator(wasmPath, input, callback) {
  var args = ["--experimental-wasm-type-reflection", runnerPath, JSON.stringify(input)];
  var child;
  try {
    child = spawn(process.execPath, args, { stdio: ["ignore", "pipe", "pipe"] });
  } catch (e) {
    return callback(e);
  }

  var stdout = "";
  var stderr = "";
  child.stdout.on("data", function(chunk) { stdout += chunk; });
  child.stderr.on("data", function(chunk) { stderr += chunk; });
  child.on("error", callback);
  child.on("close", function() {
    var parsed;
    try {
      parsed = JSON.parse(stdout);
    } catch (e) {
      return callback(new Error("dtls auth runner produced no result" +
        (stderr ? ": " + stderr.slice(0, 200) : "")));
    }
    if (parsed.error) return callback(new Error(parsed.error));
    callback(null, parsed.value);
  });
}

// fingerprint: the `a=fingerprint:sha-256` value (colon-separated hex).
function generate(fingerprint, options, callback) {
  options = options || {};
  var device = e2eeState.loadDevice(options.e2eeDevicePath);
  if (!device || !device.identity_key_pub || !device.identity_key_priv) {
    return callback(new Error("no E2EE device with identity keys is available"));
  }
  ensureWasm(options, function(err, wasmPath) {
    if (err) return callback(err);
    runGenerator(wasmPath, {
      wasmPath: wasmPath,
      fingerprint: fingerprint,
      identityKeyPub: device.identity_key_pub,
      identityKeyPriv: device.identity_key_priv,
      userId: options.userId || device.jid_user || device.facebook_uuid || "",
      // The authentication info carries the *E2EE device id* (jid_device),
      // which the peer uses to look up our identity key; the registration id
      // would make their verification fail.
      deviceId: options.deviceId != null
        ? options.deviceId
        : (device.jid_device != null ? device.jid_device : device.registration_id)
    }, callback);
  });
}

// Inserts `a=x-dtls-auth:<value>` into an SDP offer/answer (session level,
// like the web client does). Leaves SDPs that already carry it untouched.
function addToSdp(sdp, options, callback) {
  if (!sdp || sdp.indexOf("a=x-dtls-auth:") !== -1) {
    return callback(null, sdp);
  }
  var match = /a=fingerprint:sha-256 ([0-9A-Fa-f:]+)/.exec(sdp);
  if (!match) {
    return callback(new Error("the SDP has no sha-256 fingerprint"));
  }

  generate(match[1], options, function(err, value) {
    if (err) return callback(err);
    var lines = sdp.split(/\r?\n/);
    var insertAt = lines.findIndex(function(line) { return line.indexOf("m=") === 0; });
    if (insertAt === -1) insertAt = lines.length;
    lines.splice(insertAt, 0, "a=x-dtls-auth:" + value);
    callback(null, lines.join("\r\n"));
  });
}

module.exports = {
  generate: generate,
  addToSdp: addToSdp,
  ensureWasm: ensureWasm,
  wasmURL: wasmURL
};
